### ISSUE TITLE
Pgrep qemu-system is not robust

### ISSUE THREAD

**Issue by disconnect3d** [martinradev/gdb-pt-dump#22]
Currently, gdb-pt-dump parses the output of `pgrep qemu-system` which is not robust if there are multiple PIDs returned.

Is there any better we can do here?

Relevant issue: https://github.com/pwndbg/pwndbg/issues/1587#issuecomment-1438379102

**Comment by gsingh93** [comment]
I looked through the QEMU docs and didn't see anything that would allow you to get the PID directly. There is a `-pidfile` flag, but it would be annoying to ask users to set that.

Can we just use a tool like `netstat` or `ss` to get the PID?

```
❯ ss -tlpn | grep qemu-system
LISTEN 0      1            0.0.0.0:1234       0.0.0.0:*    users:(("qemu-system-aar",pid=2684768,fd=12))
LISTEN 0      1            0.0.0.0:1235       0.0.0.0:*    users:(("qemu-system-x86",pid=2749275,fd=15))
LISTEN 0      1               [::]:1234          [::]:*    users:(("qemu-system-aar",pid=2684768,fd=13))
LISTEN 0      1               [::]:1235          [::]:*    users:(("qemu-system-x86",pid=2749275,fd=16))
```

In GDB there should be a way to find the QEMU remote port that you're connected to, and then from that you can match it to the right PID in this output.
