### ISSUE TITLE
Same name of package and its file may lead to NAMESPACE COLLISION

### ISSUE THREAD

**Issue by lilian-lilifox** [martinradev/gdb-pt-dump#29]
![photo_2024-03-25_22-04-18](https://github.com/martinradev/gdb-pt-dump/assets/105332401/a30fe3ef-6174-432d-aefc-a7b4f63ad859)
This issue occurred when I was using pwndbg on archlinux, when it calls "import pt".
And the package is installed by "pacman -S python-pt" 

![Screenshot__](https://github.com/martinradev/gdb-pt-dump/assets/105332401/526cbb0c-4c56-4e11-9c75-6f17cb407b54)
 And sometimes，it works with import "pt.pt"(only when i rename the "pt" site-package and rename it back without closing the terminal thus the environment could not detect the pt.py in directory temporarily).
But this is not a very good solution.

Thank you for your attention to this issue.

**Comment by martinradev** [comment]
Thanks Lilian

IIUC, there's a clash between the 'pt/' folder and the package name 'pt'.

I should have probably required that the package name be 'pt_dump'.
This is a bit too much work now to update all packages and dependent software (like pwndbg).

I think the simplest would be to update the 'pt' folder to 'pt_lib' since today it only contain common code that's used by the gdb frontend and host frontend.

@patryk4815 What are your thoughts on this?

**Comment by patryk4815** [comment]
@martinradev  it depends what you have in `__init__.py`
https://github.com/martinradev/gdb-pt-dump/commit/21158ac3f9b36d0e5e0c86193e0ef018fc628e74

<img width="493" alt="image" src="https://github.com/martinradev/gdb-pt-dump/assets/3074260/f9b98e6f-eff4-43aa-a7cb-c1a3575443d6">
^ this was available by using `from pt import PageTableDump`

If you want export everything just add into `__init__.py`:
`from pt.pt import *`

**Comment by patryk4815** [comment]
@martinradev Look.
> This issue occurred when I was using pwndbg on archlinux, when it calls "import pt".

Author mention this issue happen only for archlinux. Becouse pwndbg use older gdb-pt-dump version.
(archlinux messup to not strict with proper version what we use in pwndbg)

**Comment by disconnect3d** [comment]
Perhaps we should call @anthraxx here who maintains the Pwndbg package in Arch Linux.

**Comment by anthraxx** [comment]
Arch Linux packages the latest commit, which pwndbg seems to require an older version. I'd say it would be best if we can adjust pwndbg and bump the references version to support latest pt-dunp... We all know latest is greatest 😸😸😸

**Comment by martinradev** [comment]
@lilian-lilifox Anything still necessary for this issue?

If no, let's close it

**Comment by lilian-lilifox** [comment]
It seem that everything works well.
Thank you for taking the time to fix it.
(^_^)
