### ISSUE TITLE
Print physical addresses in page table list

### ISSUE THREAD

**Issue by gsingh93** [martinradev/gdb-pt-dump#8]
Can you also print out the physical address each virtual address maps to? Just looking at the code for `AArch64_Block`, it seems like we can just print `self.phys` to get this information.

**Comment by martinradev** [comment]
Something like this?

`pwndbg> pt
           Virt Addr :    Length :          Phys Addr   Permissions          
            0x400000 :   0x30000 |           0x16c000 | W:0 X:1 S:0 UC:0 WB:1
            0x450000 :   0x30000 |           0x1db000 | W:0 X:1 S:0 UC:0 WB:1
            0x4b0000 :   0x37000 |           0x23b000 | W:0 X:1 S:0 UC:0 WB:1
            0x6ed000 :    0x2000 |          0x59f9000 | W:1 X:0 S:0 UC:0 WB:1
            0x6f0000 :    0x3000 |          0x59ff000 | W:1 X:0 S:0 UC:0 WB:1
            0xb23000 :    0x4000 |          0x59f5000 | W:1 X:0 S:0 UC:0 WB:1
      0x7ffd79c99000 :    0x2000 |          0x59ee000 | W:1 X:0 S:0 UC:0 WB:1
  0xffff8fa100000000 :   0x99000 |                0x0 | W:1 X:0 S:1 UC:0 WB:1`
  
The current design favors compactly printing the virtual address space.
Adding info on the physical address space rather makes the data misleading, or removes the benefit of contact printing.
This is misleading because the printed out virtual ranges are virtually-contiguous but not physically contiguous.

What problem are you having?
Maybe there's another way to solve it.

**Comment by gsingh93** [comment]
> This is misleading because the printed out virtual ranges are virtually-contiguous but not physically contiguous.

I don't see how this is misleading, isn't this completely expected behavior?

In any case, I wouldn't mind if this functionality was behind a flag (`pt -phys`) or if there was a verbose option (`pt -v`).

> What problem are you having?

1) Understanding how physical pages are being allocated requires me to see the physical page addresses. The kernel does this differently for different regions of virtual addresses, different architectures, and even at different times during the initialization process, so seeing the physical addresses would help get a sense of what's going on.
2) The `pt -find_alias` command is useful, but I would like to see more "raw" information to understand why pages that I think should be aliased are not actually aliased.

**Comment by martinradev** [comment]
Apologies for getting back to this so late.

Would rather some kind of inverse mapping (phys to virt, one to many)?
I think we could expose this in at least two ways:
1) Add a new option: `pt -phys_to_virt 0x....` which shows all virtual mappings a physical address is part of
2) Add a new option to generate the page table in some kind of format which can then be visualized with an external tool.

1) shouldn't be difficult to implement.

Are you still interested in this feature?

**Comment by martinradev** [comment]
Hey! Thanks for reminding me and the interest.

I could experiment with a few options and see how they behave with a Linux and Windows VM.

On top of my mind three things could be added:

**"pt -phys_verbose"**

This will do the following:

- Discontig phys ranges will block merging contig virt ranges. A given printed range will have the following properties: virt contiguous (no change), phys contiguous (new), page meta flags need to roughly match (no change). This will lead to more virt ranges being printed out, but the info will also be accurrate.

- start physical address will be printed

**pt -follow_va 0xfffffba0001234**

This will follow the translation path and print out the info used fo form the address.
Something like:
CR3 = 0x... | meta info
    PML4[137] = 0x.... | meta info
       PDPT[24] = 0x... | meta info
          PD[30] = 0x.... | meta info
 

@gsingh93 
Would this work for you?

**Comment by gsingh93** [comment]
Yea, I think the phys_verbose flag would work for my use case.

**Comment by martinradev** [comment]
It's work in progress:

pwndbg> pt -walk 0x200000
Page table walk for VA = 0x200000
----------------------------------
Stage 0: CR3 = 0x100000
Stage 1:   PML4[0] = 0x101023
Stage 2:     PDP[0] = 0x102023
Stage 3:       PD[1] = 0x104003
Stage 4:         PT[0] = 0x200001

pwndbg> pt -has 0x200000
   Address :    Length   Permissions          
  0x200000 : 0xfe00000 | W:0 X:1 S:1 UC:0 WB:1

**Comment by martinradev** [comment]
Progress for aarch64:
```
pwndbg> pt
           Address :  Length  User space    Kernel space 
          0x400000 : 0x40000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x450000 : 0x70000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x500000 : 0x20000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x550000 : 0x10000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x570000 : 0x20000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x5a0000 : 0x4f000   R:1 W:0 X:1   R:1 W:0 X:0 
          0x5fe000 :  0x4000   R:1 W:0 X:0   R:1 W:0 X:0 
          0x602000 :  0x3000   R:1 W:1 X:0   R:1 W:1 X:0 
          0x605000 :  0x1000   R:1 W:0 X:0   R:1 W:0 X:0 
          0x606000 :  0x1000   R:1 W:1 X:0   R:1 W:1 X:0 
          0x607000 :  0x1000   R:1 W:0 X:0   R:1 W:0 X:0 
        0x36d1f000 :  0x8000   R:1 W:1 X:0   R:1 W:1 X:0 
        0x36d2e000 :  0x1000   R:1 W:0 X:0   R:1 W:0 X:0 
    0xffffa826c000 :  0x1000   R:1 W:0 X:1   R:1 W:0 X:0 
    0xffffe5208000 :  0x2000   R:1 W:0 X:0   R:1 W:0 X:0 
    0xffffe520a000 :  0x2000   R:1 W:1 X:0   R:1 W:1 X:0 
    0xffffe520c000 :  0x1000   R:1 W:0 X:0   R:1 W:0 X:0 
0xfffffdfffe5fa000 :  0x1000   R:0 W:0 X:0   R:1 W:0 X:1 
pwndbg> pt -walk 0xfffffdfffe5fa000
Page table walk for VA = 0xfffffdfffe5fa000
--------------------------------------------
Stage 0: TTBR1_EL1 = 0x4180d000
Stage 1:   Layer-0[507] = 0x42521003
Stage 2:     Layer-1[511] = 0x42522003
Stage 3:       Layer-2[498] = 0x42523003
Stage 4:         Layer-3[506] = 0x4106e783

pwndbg> pt -walk 0x36d2e000
Page table walk for VA = 0x36d2e000
------------------------------------
Stage 0: TTBR0_EL1 = 0x43471000
Stage 1:   Layer-0[0] = 0x43452003
Stage 2:     Layer-1[0] = 0x43453003
Stage 3:       Layer-2[438] = 0x434fe003
Stage 4:         Layer-3[302] = 0x41dcafc3

```

**Comment by martinradev** [comment]
@gsingh93 

I pushed the implementation on https://github.com/martinradev/gdb-pt-dump/pull/new/walk

Could you please give it a try?

Here's an example with Linux aarch64:
```
pwndbg> pt -walk 0xfffffdffffe00000
Page table walk for VA = 0xfffffdffffe00000
-------------------------------------------
TTBR1_EL1 = 0x4180f000
  Level0[507] = 0x420bb000        | Flags 0x003
    Level1[511] = 0x420bc000      | Flags 0x003
      Level2[511] = 0x5c000000    | Flags 0x701
```

```
pwndbg> pt -phys_verbose                                                                                 
           Address :         Length :         Phys | User space  | Kernel space 
0xffff000000000000 :       0x200000 :   0x40000000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
0xffff000001810000 :       0xcd3000 :   0x41810000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff0000024e3000 :         0x1000 :   0x424e3000   R:0 W:0 X:0   R:1 W:0 X:0  
0xffff0000024e4000 :       0xeaa000 :   0x424e4000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff00000338e000 :         0x5000 :   0x4338e000   R:0 W:0 X:0   R:1 W:0 X:0  
0xffff000003393000 :     0x1cc6d000 :   0x43393000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff800000000000 :         0x1000 :   0x424e3000   R:0 W:0 X:0   R:1 W:0 X:1  
0xffff800008e80000 :         0x1000 :   0x4338e000   R:0 W:0 X:0   R:1 W:0 X:1  
0xffff800008e81000 :         0x2000 :   0x4338f000   R:0 W:0 X:0   R:1 W:0 X:0  
0xffff800008e83000 :         0x2000 :   0x43391000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff800010000000 :       0xe80000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:1  
0xffff800010e80000 :       0x790000 :   0x41080000   R:0 W:0 X:0   R:1 W:0 X:0  
0xffff800011c00000 :       0x350000 :   0x41e00000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff800011f51000 :         0x1000 :    0x8020000   R:0 W:0 X:0   R:1 W:1 X:0  
0xffff800011f53000 :         0x1000 :   0x424e2000   R:0 W:0 X:0   R:1 W:1 X:0  
```

**Comment by martinradev** [comment]
A few more examples:

```
pwndbg> pt -has 0xffff800011f51000 -phys_verbose
           Address :         Length :         Phys | User space  | Kernel space 
0xffff800011f51000 :         0x1000 :    0x8020000   R:0 W:0 X:0   R:1 W:1 X:0  
```

```
Found at 0xffff0000010800f8 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000010892e8 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001089300 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000015e1eb0 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000015e2c1a in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000015ec3b4 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001611758 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001611770 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016118a0 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016118b8 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001653580 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016535aa in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016536b4 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016536c9 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016ab222 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000016ab2c7 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001704b64 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001729c6b in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff00000172a0b9 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff0000018098e0 in 0xffff000000200000 :      0x1610000 :   0x40200000   R:0 W:0 X:0   R:1 W:0 X:0  
Found at 0xffff000001d8504e in 0xffff000001810000 :       0xcd3000 :   0x41810000   R:0 W:0 X:0   R:1 W:1 X:0  
Found at 0xffff000001de3970 in 0xffff000001810000 :       0xcd3000 :   0x41810000   R:0 W:0 X:0   R:1 W:1 X:0  
```

**Comment by martinradev** [comment]
I just merged the patches for "-walk" and "-phys_verbose" to the master branch.

There were also quite a few fixes for x86-32, aarch64 and riscv64, followed with integration tests.

Could you please check, so that I could close this request?

**Comment by martinradev** [comment]
Patches are long merged. Closing.
